### ISSUE TITLE
封装vue版本的echarts只是为了使用上的便捷么？

### ISSUE THREAD

**Issue by cajan** [xlsdg/vue-echarts-v3#10]
你好！如题，你这个项目除了在vue中使用echarts方便一些之外，还有解决其他问题或者基于什么原因封装的？我之前在vue中使用echarts，在IE中init初始化时会出现奇怪报错，chrome正常，查不到原因，接下来想用你这个试试

**Comment by xlsdg** [comment]
1. 轻量, 高效, 按需绑定事件;（如你所说的使用上便捷）
2. 支持按需引入 ECharts.js 的图表和组件;（同样是使用上便捷）
3. 支持组件 resize 事件自动更新视图;（原版echarts不支持，本插件添加的功能，为了满足缩放页面元素的时候自动更新图表）

**Comment by aalexlin** [comment]
你好，和官网一样的配置，line类型图表，无载入动画，而官网有。

**Comment by cajan** [comment]
好的谢谢你的回复，这么久才响应抱歉...
