### ISSUE TITLE
怎样引入echarts的插件

### ISSUE THREAD

**Issue by iamwelk** [xlsdg/vue-echarts-v3#14]
我想在项目中引入[echarts-wordCloud](https://github.com/ecomfe/echarts-wordcloud),但是好像不成功，请问是什么原因？
![image](https://cloud.githubusercontent.com/assets/6983075/25223461/0403af9c-25ee-11e7-8897-f299eaacf646.png)
![image](https://cloud.githubusercontent.com/assets/6983075/25223473/0ac8b0f2-25ee-11e7-8eac-496927dee190.png)

**Comment by xlsdg** [comment]
wordCloud is not supported yet in v3.0.2

https://github.com/ecomfe/echarts/issues/2573
