### ISSUE TITLE
Can't get dom width or height

### ISSUE THREAD

**Issue by sword865** [xlsdg/vue-echarts-v3#16]
运行了readme.md的例子，但是报错说：Can't get dom width or height
图表也不显示。
请问是什么原因?

**Comment by xlsdg** [comment]
重新检查一下自己的操作步骤

```bash
$ git clone https://github.com/xlsdg/vue-echarts-v3.git vue-echarts
$ cd vue-echarts && npm i && npm run start
```

**Comment by sword865** [comment]
这个可以运行的，我试了，但是按readme.md写的那个例子不行

**Comment by sword865** [comment]
<template>
       <div class="echarts">
           <IEcharts :option="bar" :loading="loading" @ready="onReady" @click="onClick"></IEcharts>
        <button @click="doRandom">Random</button>
       </div>
    </template>
    .....
    <style scoped>
        .echarts {
            width: 400px;
            height: 400px;
        }
    </style>

这个

**Comment by xlsdg** [comment]
那就要自己仔细检查一下工程的代码配置

**Comment by sword865** [comment]
好的，我在研究一下

**Comment by lin-xin** [comment]
@sword865 找到问题了吗？我也遇到这种情况

**Comment by lin-xin** [comment]
从v1.0.3 升级到 v1.0.4 就会出现这个问题

**Comment by xlsdg** [comment]
@lin-xin 有示例代码仓库地址吗？或者新建一个提交一下你的demo代码？我帮忙定位看看

**Comment by tsunamilx** [comment]
> 从 v1.0.3 升级到 v1.0.4 就会出现这个问题

+1

**Comment by zhang6685979** [comment]
请问这个问题解决了，我也也遇到了这个问题

**Comment by xlsdg** [comment]
@zhang6685979 能发一下你的工程 `package.json` 文件的内容吗？方便定位一下问题。

**Comment by Hardcore0331** [comment]
我也出现了一样的情况

**Comment by xlsdg** [comment]
@Hardcore0331 有工程示例代码吗？

**Comment by Hardcore0331** [comment]
问题解决了，父组件的问题，跟echarts没关系，多谢
