### ISSUE TITLE
违反 MIT 协议

### ISSUE THREAD

**Issue by Justineo** [xlsdg/vue-echarts-v3#17]
很明显，这个项目是基于老版本的 [Vue Echarts](https://github.com/Justineo/vue-echarts) 修改的，README 中只字不提也就算了，毕竟 License 没有强制要求。不过最低的要求至少应该满足吧，需要在 LICENSE 中附上原项目 LICENSE 全文（当然也包括原作者的名字），而不是把我的名字改成你自己就 OK 了。

[协议要求](https://github.com/Justineo/vue-echarts/blob/8006a5d60a8c47e2ee8ab0cafb2b0c8c557ed749/LICENSE#L12-L13)：

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

**Comment by xlsdg** [comment]
非常谢谢您提的 issue，让我意识到了自己在开源协议这一块的理解欠缺。该组件的封装很多想法都借鉴了您的作品 [vue-echarts](https://github.com/Justineo/vue-echarts)，并针对自己的需求做了优化，在此表示感谢。对您造成不必要的烦恼，深表歉意，我会尽快修正问题并积极听取您的意见和建议，共同学习进步。
