### ISSUE TITLE
是不是有依赖关系

### ISSUE THREAD

**Issue by shijunti19** [xlsdg/vue-echarts-v3#18]
你用了vue2.3.2导致我们无法升级到vue最新版本
就是你不更新到最新，我们升级到vue最新就提示出错

**Comment by xlsdg** [comment]
好，我现在把vue的版本降下来，再发一个新的版本

**Comment by xlsdg** [comment]
想了想降版本的方式并不是最好的解决办法，降到哪个版本会比较好，说不准。

最好的方式是直接引入源文件。

1.加载全部模块：
```vue
import IEcharts from 'vue-echarts-v3/src/full.vue';
```

2.加载基础模块：
```vue
import IEcharts from 'vue-echarts-v3/src/lite.vue';
```

这样就可以很好的解决任意低版本，用工程自带的 vue 版本去编译组件。

试试看这样能不能解决你的问题。

**Comment by shijunti19** [comment]
好，我切换下
