### ISSUE TITLE
Error: `setOption` should not be called during main process

### ISSUE THREAD

**Issue by echoyuanliang** [xlsdg/vue-echarts-v3#19]
我用vue2.0和vue-echarts-v3的line模块，报错Error: `setOption` should not be called during main process。 相关代码

`
       

        <IEcharts :option="charts"></IEcharts>

         import IEcharts from 'vue-echarts-v3/src/lite.vue';
         export default{
         components: {
              IEcharts
         },

        data: function () {
            return {
                net_info: {},
                iface_status: [],
                connections: {},
                charts: {
                    title : {
                        text : '网卡流量'
                    },

                    tooltip: {
                        trigger: 'axis',
                        formatter: function (params) {
                            params = params[0];
                            var date = new Date(params.name);
                            return date.getHours()+ ':' + date.getMinutes() + ':' + date.getSeconds() + ' : ' + params.value[1];
                        },
                        axisPointer: {
                            animation: false
                        }
                    },

                    xAis: {
                        type: 'time',
                        splitLine: {
                            show: false
                        }
                    },

                    yAxis: {
                        type: 'value',
                        boundaryGap: [0, '100%'],
                        splitLine: {
                            show: false
                        }
                    },

                    series: [{
                        name: '网卡流量',
                        type: 'line',
                        showSymbol: false,
                        hoverAnimation: false,
                        data: []
                    }]

                }
            };
        },

        methods: {
            getNetworkInfo: function () {
                api.network.get().then((response)=>{
                    this.net_info = response.data.data;
                    //console.log(this.net_info);
                    this.iface_status = this.net_info.iface_status;
                    this.connections = this.net_info.connections;
                    const data_point = this.generateEchartsData(this.iface_status);
                    this.charts.series[0].data.push(data_point);

                }, (error)=>{
                    // console.log(error);
                });
            },

            generateEchartsData: function (iface_info) {
                let  now = new Date();
                return {
                    name: now.toString(),
                    value: [
                        [now.getHours(), now.getMinutes() , now.getSeconds()].join(':'),
                        Math.round(iface_info[1].receive_bytes)
                    ]
                }
            },

            getIfaceStatus: function () {
                api.iface_status.get().then((response)=>{
                    this.iface_status = response.data.data;
                    const data_point = this.generateEchartsData(this.iface_status);
                    this.charts.series[0].data.push(data_point);
                }, (error)=>{

                });
            },
        },

        mounted: function () {
            this.$log.log('mounted');
            this.getNetworkInfo();

            // set interval
            const interval = 6000; // 1minutes
            setInterval(this.getIfaceStatus, interval);
        }
    }
`

**Comment by xlsdg** [comment]
这好像是 echarts 的问题：https://github.com/ecomfe/echarts/issues/3806 和 https://github.com/ecomfe/echarts/issues/5093

**Comment by Huberyfight** [comment]
解决了吗？我也遇到这个问题了。。，用的是3.7.1

**Comment by dongsir** [comment]
@xlsdg 应该和echarts没关系。 'vue-echarts-v3/src/lite.vue'报错，'vue-echarts-v3/src/full.vue'就正常。

@Huberyfight 也是同样的问题，有点费解。
