### ISSUE TITLE
请问能把 echarts的扩展库整合进去吗？

### ISSUE THREAD

**Issue by 188007803** [xlsdg/vue-echarts-v3#22]
比如：字符云 wordcloud，如果需要手动整合，该怎么做呢？ 谢谢！

**Comment by xlsdg** [comment]
最新版 echarts 不支持 wordcloud 扩展库，参考 https://github.com/xlsdg/vue-echarts-v3/issues/14

**Comment by 188007803** [comment]
谢谢！看来得用原始的 wordcloud2.js 来做了。
