### ISSUE TITLE
异步加载数据时，一直提示Error in nextTick

### ISSUE THREAD

**Issue by hk5518** [xlsdg/vue-echarts-v3#23]
Error in nextTick: "Error: Series has not been initialized yet."

**Comment by xlsdg** [comment]
麻烦贴一下代码，只发报错信息没办法定位问题。

**Comment by hk5518** [comment]
**1、示图文件代码**
`<template>
	<div class="echarts">
		<IEcharts :option="option" :loading="loading" @ready="onReady"  @click="onClick"></IEcharts>
	</div>
</template>

<style>
.echarts {
	width: 800px;
	height: 400px;
}
</style>

<script>
import IEcharts from 'vue-echarts-v3/src/full.vue';
import { mapState } from 'vuex';
export default {
	components: {
		IEcharts
	},
	data: () => ({
		loading: false
	}),
	mounted() {
		this.$store.dispatch('fetchEcharts');
	},
	computed: {
		...mapState({
			option:state=>state.bar.option
		})
	},
	methods: {
		onReady(instance) {
		},
		onClick(event, instance, echarts) {
		}
	}
};
</script>`

**2、vuex代码**
`import http from '@/utils/http';
export default {
  state: {
		option: {},
		loading:false
	},
  mutations: {
    queryEcharts(state, result) {
			state.option=result;
    }
  },
  actions: {
    fetchEcharts({ commit }, payload) {
			http({
				url:'static/data/echarts/bar.json',
				method:'get'
			}).then(res=>{
				const result=res.data;
      	commit('queryEcharts', result);
			});
    }
  },
};`

**Comment by hk5518** [comment]
**1、视图文件代码**
```
<template>
	<div class="echarts">
		<IEcharts :option="option" :loading="loading" @ready="onReady"  @click="onClick"></IEcharts>
	</div>
</template>

<style>
.echarts {
	width: 800px;
	height: 400px;
}
</style>

<script>
import IEcharts from 'vue-echarts-v3/src/full.vue';
import { mapState } from 'vuex';
export default {
	components: {
		IEcharts
	},
	data: () => ({
		loading: false
	}),
	mounted() {
		this.$store.dispatch('fetchEcharts');
	},
	computed: {
		...mapState({
			option:state=>state.bar.option
		})
	},
	methods: {
		onReady(instance) {
		},
		onClick(event, instance, echarts) {
		}
	}
};
</script>
```
**2、vuex代码**

```
import http from '@/utils/http';
export default {
  state: {
		option: {},
		loading:false
	},
  mutations: {
    queryEcharts(state, result) {
			state.option=result;
    }
  },
  actions: {
    fetchEcharts({ commit }, payload) {
			http({
				url:'static/data/echarts/bar.json',
				method:'get'
			}).then(res=>{
				const result=res.data;
      	commit('queryEcharts', result);
			});
    }
  },
};
```

**Comment by xlsdg** [comment]
建议在有数据的时候，再加载图表组件，比如用 `v-if` 判断。

**Comment by xlsdg** [comment]
或者初始化的时候给图表空的数据 `option` ：

```js
    bar: {
        title: {
          text: 'ECharts Hello World'
        },
        tooltip: {},
        xAxis: {
          data: []
        },
        yAxis: {},
        series: [{
          name: 'Sales',
          type: 'bar',
          data: []
        }]
      }
```

获取到数据之后，再往 `bar.xAxis.data` 和 `series[0].data` 中 `push` 数据。

**Comment by hk5518** [comment]
采用动态组件加载比较方便，已经解决了！多谢了！

**Comment by catnoodle** [comment]
@hk5518 请问下你说的动态组件是啥？
