### ISSUE TITLE
Vue-Echarts-v3 is not working in IE9+ , only working in chrome/firefox

### ISSUE THREAD

**Issue by Narayana84** [xlsdg/vue-echarts-v3#25]
Echarts.vue + Error in mounted hook: "TypeError: Invalid calling object"
TypeError: Invalid calling object
 at Animation.prototype._startLoop (eval code:177:13)
at Animation.prototype.start (eval code:188:13)

Any help appreciated!

**Comment by xlsdg** [comment]
see https://github.com/ecomfe/zrender/pull/235
