### ISSUE TITLE
bug: breaking change between 1.0.3 and 1.0.4

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [xlsdg/vue-echarts-v3#26]
I suppose there is a a breaking bug between 1.0.3 and 1.0.4, since my echarts components won't be displayed anymore. Reverting to 1.0.3 resolve the problem.

**Comment by xlsdg** [comment]
There are something different between `1.0.3` and `1.0.4` :
![0](https://cloud.githubusercontent.com/assets/1203305/26535467/5a6bc85c-4460-11e7-91ed-402aba5ca920.png)
![1](https://cloud.githubusercontent.com/assets/1203305/26535468/5a762612-4460-11e7-9936-f1698f9b4c32.png)
![2](https://cloud.githubusercontent.com/assets/1203305/26535469/5a8b247c-4460-11e7-962f-ecf5a18d32ba.png)
![3](https://cloud.githubusercontent.com/assets/1203305/26535470/5ad272e6-4460-11e7-9e30-9e25b38e5af2.png)
![4](https://cloud.githubusercontent.com/assets/1203305/26535495/9c8e74c8-4460-11e7-8845-c595a03063c6.png)

**Comment by eljefedelrodeodeljefe** [comment]
Yeah, I realized those changes. I think it might have something todo with how the `full.js` export is altered, but I am no expert on Webpack.

Here is my component:
```js
import IEcharts from 'vue-echarts-v3'

export default {
  data () {
    const colors = ['#5793f3', '#d14a61', '#675bba']
    return {
      loading: false,
      bar: {
        title: {
          text: 'Tiny IoT Cloud'
        },
        color: colors,
        tooltip: {
          trigger: 'none',
          axisPointer: {
            type: 'cross'
          }
        },
        legend: {
          data: ['Temperature over time, realtime']
        },
        grid: {
          top: 70,
          bottom: 50
        },
        xAxis: [
          {
            type: 'category',
            axisTick: {
              alignWithLabel: true
            },
            axisLine: {
              onZero: false,
              lineStyle: {
                color: colors[1]
              }
            },
            axisPointer: {
              label: {
                formatter: function (params) {
                  return 'Point ' + params.value + '：' + params.seriesData[0].data
                }
              }
            },
            data: [1490537651675]
          }
        ],
        yAxis: [
          {
            type: 'value'
          }
        ],
        series: [
          {
            name: 'Temperature Realtime',
            type: 'line',
            smooth: true,
            data: [10]
          }
        ]
      },
      ws: null,
      mockInterval: null
    }
  },
  mounted () {},
  methods: {},
  components: {
    IEcharts
  }
}
```

**Comment by xlsdg** [comment]
Can you give me the contents of `package.json`?
