### ISSUE TITLE
请问echarts中的热力图如何用这个实现，谢谢

### ISSUE THREAD

**Issue by zhang6685979** [xlsdg/vue-echarts-v3#27]

**Comment by xlsdg** [comment]
请问是哪一种热力图？

![image](https://user-images.githubusercontent.com/1203305/26971005-1872aa42-4d3e-11e7-8090-4406a96b4bd8.png)

**Comment by zhang6685979** [comment]
你好，是第一种热力图，支持么？

**Comment by xlsdg** [comment]
官方示例都是支持的。

**Comment by zhang6685979** [comment]
恩，知道了，我自己实现了，这个热力图需要引入百度地图的api,还有一个问题就是我按需引入lite.vue会报一个警告，这个怎么去掉

vue.esm.js?8910:434 [Vue warn]: "style" is a reserved attribute and cannot be used as component prop.

found in

---> <IEcharts> at F:\MyProject\city-platform\node_modules\_vue-echarts-v3@1.0.3@vue-echarts-v3\src\lite.vue
       <HeatMap> at F:\MyProject\city-platform\src\components\heatMap.vue
         <App> at F:\MyProject\city-platform\src\App.vue
           <Root>

**Comment by xlsdg** [comment]
升级到 1.0.4 版本试试

**Comment by zhang6685979** [comment]
可以了，谢谢
