### ISSUE TITLE
按需引用图表和组件会报错。

### ISSUE THREAD

**Issue by ThinkRealize** [xlsdg/vue-echarts-v3#3]
错误堆栈：

Uncaught ReferenceError: __DEV__ is not defined
    at Function.RootClass.extend (eval at <anonymous> (app.js:834), <anonymous>:69:13)
    at Function.entity.extend (eval at <anonymous> (app.js:834), <anonymous>:236:56)
    at eval (eval at <anonymous> (app.js:4202), <anonymous>:16:30)
    at Object.<anonymous> (app.js:4202)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at eval (eval at <anonymous> (app.js:768), <anonymous>:3:24)
    at Object.<anonymous> (app.js:768)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
RootClass.extend @ clazz.js?3e66:69
entity.extend @ clazz.js?3e66:236
(anonymous) @ Ordinal.js?3a6b:16
(anonymous) @ app.js:4202
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ axisHelper.js?4730:3
(anonymous) @ app.js:768
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ Grid.js?f167:9
(anonymous) @ app.js:1891
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ bar.js?931c:5
(anonymous) @ app.js:3619
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ echarts.js?ec46:10
(anonymous) @ app.js:2899
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ main.js?3479:6
(anonymous) @ app.js:2917
__webpack_require__ @ app.js:556
fn @ app.js:87
(anonymous) @ app.js:587
__webpack_require__ @ app.js:556
(anonymous) @ app.js:579
(anonymous) @ app.js:582

// 引用

import 'echarts/lib/chart/bar'
import 'echarts/lib/chart/pie'

import 'echarts/lib/chart/lines'
import 'echarts/lib/component/grid'
import 'echarts/lib/component/legend'
import 'echarts/lib/component/tooltip'

import 'echarts/lib/component/title'

import 'echarts/lib/component/dataZoom'
import 'echarts/lib/component/visualMap'
import 'echarts/lib/component/toolbox'

**Comment by xlsdg** [comment]
Uncaught ReferenceError: DEV is not defined 检查一下自己的代码

**Comment by ThinkRealize** [comment]
按需引用图表和组件后必须使用，也就是在项目中 import IEcharts from 'vue-echarts-v3/src/lite.vue',  否则会报这个错误
