### ISSUE TITLE
any idea how to get a chart like this one?

### ISSUE THREAD

**Issue by ralyodio** [xlsdg/vue-echarts-v3#33]
![screenshot 2017-06-26 21 03 53](https://user-images.githubusercontent.com/27381/27570466-39e1fcfa-5ab3-11e7-84f3-c177d1f100ce.png)
https://i.imgur.com/TAihaTy.png

**Comment by xlsdg** [comment]
http://echarts.baidu.com/examples.html#chart-type-candlestick.
