### ISSUE TITLE
怎么按需引入没有用

### ISSUE THREAD

**Issue by 617450941** [xlsdg/vue-echarts-v3#37]
import IEcharts from 'vue-echarts-v3/src/full.vue'
import 'echarts/lib/chart/pie'

引入组件的页面 该加载那么大的还是那么大 页面加载的大小没有变化

总之 无论是
import IEcharts from 'vue-echarts-v3/src/full.vue'
import 'echarts/lib/chart/pie' 
上面这样引入
还是直接
import IEcharts from 'vue-echarts-v3/src/full.vue'
这样引入 都是可以用pie这个图表控件的
不知道两种方式有什么区别 总要的是 上面两种引入方式页面加载的大小是一样的

**Comment by xlsdg** [comment]
能再仔细阅读一下首页的文档吗？

按需引入是这样：

```vue
import IEcharts from 'vue-echarts-v3/src/lite.vue';
import 'echarts/lib/chart/pie'
```
