### ISSUE TITLE
报错 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by mei1992** [xlsdg/vue-echarts-v3#38]
按照readme单独做示例ok，放在我项目上就报这个错

**Comment by xlsdg** [comment]
自己谷歌一下，这个报错跟插件没有关系。

**Comment by mei1992** [comment]
好吧，谷歌结果是混用import 和插件里的module.exports，可是单独的demo也是混用的却没事，这里改了import也还不行，所以没头绪

**Comment by xlsdg** [comment]
检查一下前端工程配置吧，import 插件是没问题的。

**Comment by mei1992** [comment]
应该是因为.babelrc里的  "plugins": ["transform-runtime"]，可以了

**Comment by mei1992** [comment]
import IEcharts from 'vue-echarts-v3/src/lite.vue';
import 'echarts/lib/chart/bar'
奇怪的是，这样按需引入bar后打包的js文件，比我直接用echart打包的公共js文件还要大，这应该怎么解释呢？求教~

**Comment by mei1992** [comment]
不好意思，上面也是我写的有问题，改过来按着你的按需引入样例写，报这个错：Error in nextTick: "Error: Component series.bar not exists. Load it first."

**Comment by xlsdg** [comment]
那就是你没引入 `bar`：

```js
import 'echarts/lib/chart/bar';
```

**Comment by mei1992** [comment]
好吧，问题是，这个确定引入了，跟着你样例来的

**Comment by xlsdg** [comment]
检查一下代码吧！

**Comment by cooe** [comment]
在使用地图时，能够使用简单的地图，但是在地图上显示线或者点的时候会出现错误，比如说：我们使用地图来显示人口迁移时，无法使用地图，出现错误

**Comment by xlsdg** [comment]
是什么报错？具体点
