### ISSUE TITLE
Errors appear when redirect to another page that don't have charts

### ISSUE THREAD

**Issue by TKafassis** [xlsdg/vue-echarts-v3#44]
the errors that appear are:
-Uncaught TypeError: Cannot read property 'getWidth' of null
-Uncaught Error: `setOption` should not be called during main process
I've tried to find a solution to the problem, but everything i found was in Chinese and i wasn't able to figure out what to do to fix these problems.

**Comment by xlsdg** [comment]
Show me the code.

**Comment by TKafassis** [comment]
<template>
    <div class="content">
        <div class="container" id="home_page">
            <div class="echarts">
                <IEcharts :option="pie" :resizable="true" :loading="pie_loading"
                          @ready="onPieReady">
                </IEcharts>
            </div>
        </div>
    </div>
</template>

<script type="text/babel">

    import IEcharts from 'vue-echarts-v3/src/full.vue';

    export default {
        components: {
            IEcharts
        },
        data() {
            const self = this;
            return {
                //patients age data and options
                pie_loading: true,
                patients_age_data: [],
                pie: {
                    tooltip: {
                        trigger: 'item',
                        formatter: "{b} : {c}"
                    },
                    visualMap: {
                        show: false,
                        min: 0,
                        max: 600,
                        inRange: {
                            colorLightness: [0, 1]
                        }
                    },
                    series: [
                        {
                            name: 'Ages',
                            type: 'pie',
                            radius: '70%',
                            center: ['50%', '50%'],
                            data: [],
                            labelLine: {
                                normal: {
                                    length: 2,
                                    length2: 5
                                }
                            },
                            itemStyle: {
                                normal: {
                                    color: '#095791',
                                    shadowBlur: 20,
                                    shadowColor: 'rgba(0, 0, 0, 0.3)'
                                }
                            }
                        }
                    ]
                },
            }
        },
        methods: {
            onPieReady(instance) {
                const self = this;
                self.pie_chart = instance;
            }
        },
        created() {
            const self = this;
            axios.get('/doctor_info')
                    .then(function (response) {
                        self.patients_age_data = response.data.patients_age;
                    })
                    .catch(function (error) {
                        console.log(error);
                    });
        },
        mounted () {
            const self = this;
            setInterval(function () {
                self.pie_chart && self.pie_chart.setOption({
                    series: [{
                        data: self.patients_age_data
                    }]
                });
            }, 500);

            self.pie_loading = !self.pie_loading;
        }
    }
</script>

**Comment by TKafassis** [comment]
```vue
<template>
    <div class="content">
        <div class="container" id="home_page">
            <div class="echarts">
                <IEcharts :option="pie" :resizable="true" :loading="pie_loading"
                          @ready="onPieReady">
                </IEcharts>
            </div>
        </div>
    </div>
</template>

<script type="text/babel">

    import IEcharts from 'vue-echarts-v3/src/full.vue';

    export default {
        components: {
            IEcharts
        },
        data() {
            const self = this;
            return {
                //patients age data and options
                pie_loading: true,
                patients_age_data: [],
                pie: {
                    tooltip: {
                        trigger: 'item',
                        formatter: "{b} : {c}"
                    },
                    visualMap: {
                        show: false,
                        min: 0,
                        max: 600,
                        inRange: {
                            colorLightness: [0, 1]
                        }
                    },
                    series: [
                        {
                            name: 'Ages',
                            type: 'pie',
                            radius: '70%',
                            center: ['50%', '50%'],
                            data: [],
                            labelLine: {
                                normal: {
                                    length: 2,
                                    length2: 5
                                }
                            },
                            itemStyle: {
                                normal: {
                                    color: '#095791',
                                    shadowBlur: 20,
                                    shadowColor: 'rgba(0, 0, 0, 0.3)'
                                }
                            }
                        }
                    ]
                },
            }
        },
        methods: {
            onPieReady(instance) {
                const self = this;
                self.pie_chart = instance;
            }
        },
        created() {
            const self = this;
            axios.get('/doctor_info')
                    .then(function (response) {
                        self.patients_age_data = response.data.patients_age;
                    })
                    .catch(function (error) {
                        console.log(error);
                    });
        },
        mounted () {
            const self = this;
            setInterval(function () {
                self.pie_chart && self.pie_chart.setOption({
                    series: [{
                        data: self.patients_age_data
                    }]
                });
            }, 500);

            self.pie_loading = !self.pie_loading;
        }
    }

</script>
```

**Comment by xlsdg** [comment]
try this:

```vue
<template>
    <div class="content">
        <div class="container" id="home_page">
            <div class="echarts">
                <IEcharts
                    :option="pie"
                    :resizable="true"
                    :loading="pie_loading"
                    @ready="onPieReady"
                />
            </div>
        </div>
    </div>
</template>

<script type="text/babel">
    import IEcharts from 'vue-echarts-v3/src/full.vue';

    export default {
        components: {
            IEcharts
        },
        data() {
            const self = this;
            return {
                //patients age data and options
                pie_loading: true,
                pie_chart: null,
                pie: {
                    tooltip: {
                        trigger: 'item',
                        formatter: "{b} : {c}"
                    },
                    visualMap: {
                        show: false,
                        min: 0,
                        max: 600,
                        inRange: {
                            colorLightness: [0, 1]
                        }
                    },
                    series: [
                        {
                            name: 'Ages',
                            type: 'pie',
                            radius: '70%',
                            center: ['50%', '50%'],
                            data: [],
                            labelLine: {
                                normal: {
                                    length: 2,
                                    length2: 5
                                }
                            },
                            itemStyle: {
                                normal: {
                                    color: '#095791',
                                    shadowBlur: 20,
                                    shadowColor: 'rgba(0, 0, 0, 0.3)'
                                }
                            }
                        }
                    ]
                },
            }
        },
        methods: {
            onPieReady(instance) {
                const self = this;
                self.pie_chart = instance;
            }
        },
        created() {
            const self = this;
            axios.get('/doctor_info')
                .then(function (response) {
                    self.pie_chart && self.pie.series[0].data = response.data.patients_age;
                    self.pie_loading = false;
                })
                .catch(function (error) {
                    console.log(error);
                });
        }
    }
</script>
```

**Comment by TKafassis** [comment]
this works fine with a little change
this part of the code:
self.pie_chart && self.pie.series[0].data = response.data.patients_age;
changed to that one:
self.pie.series[0].data = response.data.patients_age;
because with syntax i got Invalid left-hand side in assignment expression error
thank you very much for your help!!!
