### ISSUE TITLE
主题引用不成功

### ISSUE THREAD

**Issue by erhuo-cyy** [xlsdg/vue-echarts-v3#45]
看了另一个哥们#40 提的问题《echarts主题自定义不成功》，根据您的代码来写，设置不了主题，能帮忙看看代码有什么不对吗
![111](https://user-images.githubusercontent.com/25655557/30410385-4f18b834-993d-11e7-80e5-149c7a28a295.png)
![222](https://user-images.githubusercontent.com/25655557/30410390-54dc62e8-993d-11e7-9c37-c1c0b0bffcff.png)

**Comment by xlsdg** [comment]
按照 https://github.com/xlsdg/vue-echarts-v3/issues/40 的最后一条回复操作一遍试试。

**Comment by xlsdg** [comment]
或者尝试这样的方式引入：

```js
import IEcharts from 'vue-echarts-v3/src/full.vue';
```

或

```js
import IEcharts from 'vue-echarts-v3/src/lite.vue';
```

不用 `import IEcharts from 'vue-echarts-v3';`

**Comment by ruanzy** [comment]
import IEcharts from 'vue-echarts-v3/src/full.vue';
import 'echarts/theme/macarons.js'
报错：
Uncaught Error: Cannot find module "echarts/theme/macarons.js"

import IEcharts from 'vue-echarts-v3/src/full.vue';
import 'vue-echarts-v3/node_modules/echarts/theme/macarons.js'

这样才行

**Comment by xlsdg** [comment]
有可能跟 `webpack` 配置有关。
