### ISSUE TITLE
demo 运行报错

### ISSUE THREAD

**Issue by Just-focus** [xlsdg/vue-echarts-v3#5]
Cannot read property 'toString' of undefined

**Comment by lin-xin** [comment]
@Just-focus 我也遇到这个问题.
@xlsdg 会是因为node版本 <6 吗？我的版本是4.4.7

**Comment by xlsdg** [comment]
node v6 下也报错，我找下原因。

**Comment by newlife** [comment]
应该是vue升级到2.2问题

**Comment by xlsdg** [comment]
找到原因了，现在修复一下。

**Comment by lin-xin** [comment]
修复好了说一下

**Comment by lin-xin** [comment]
重新npm install 会是最新的吗？

**Comment by xlsdg** [comment]
版本号改成 1.0.3，重新 npm install 试试。
