### ISSUE TITLE
  "echarts.util.each()" -> "echarts is not defined" looking for help 

### ISSUE THREAD

**Issue by Yiiiiii** [xlsdg/vue-echarts-v3#53]
Hi xlsdg,
I am working on a project which involve a "Scatter on Single Axis" chart; I had some issue to set it up

*I tired to set the "echarts.util.each()" as "IEcharts.util.each()", and I got another error;

Any assistance will be deeply appreciated. 

Chart link:
https://ecomfe.github.io/echarts-examples/public/editor.html?c=scatter-single-axis
Code:

<template>
  <div class="echarts">
    <IEcharts :option="bar" :loading="loading" @ready="onReady" @click="onClick"></IEcharts>
  </div>
</template>

<script type="text/babel">

  import IEcharts from 'vue-echarts-v3/src/full.vue';

  export default {
    name: 'view',
    components: {
      IEcharts,
    },
    props: {
    },
    data: () => ({
      loading: false,
      bar: {
        tooltip: {
          position: 'top',
        },
        title: [],
        singleAxis: [],
        series: [],
      },
    }),

    mounted() {
      echarts.util.each(days, (day, idx) => {
        option.title.push({
          textBaseline: 'middle',
          top: `${(idx + 0.5) * 100 / 7}%`,
          text: day,
        });
        option.singleAxis.push({
          left: 150,
          type: 'category',
          boundaryGap: false,
          data: hours,
          top: `${idx * 100 / 7 + 5}%`,
          height: `${100 / 7 - 10}%`,
          axisLabel: {
            interval: 2,
          },
        });
        option.series.push({
          singleAxisIndex: idx,
          coordinateSystem: 'singleAxis',
          type: 'scatter',
          data: [],
          symbolSize(dataItem) {
            return dataItem[1] * 4;
          },
        });
      });

      echarts.util.each(data, (dataItem) => {
        option.series[dataItem[0]].data.push([dataItem[1], dataItem[2]]);
      });
    },

    methods: {
      onReady(instance) {
        console.log(instance);
      },
      onClick(event, instance, ...args) {
        console.log(args);
      },
    },
  };

</script>

<style scoped>
  .echarts {
    height: 600px;
    margin-top: -10px;
  }
</style>

**Comment by Yiiiiii** [comment]
fixed, onready to get dat " echarts ",  
eg:
methods: {
      onReady(instance, echarts) {

**Comment by stejones78** [comment]
Hello, I have the same problem trying to recreate this chart. I'm trying to set up "Scatter on Single Axis", I copy the code from the example but it won't load, I tried Yiiiiii's advice but can't get that to work either.

**Comment by ashrafmansuri123** [comment]
> fixed, onready to get dat " echarts ",
> eg:
> methods: {
> onReady(instance, echarts) {


hi didnt understand proper , please give full solution
