### ISSUE TITLE
line类型图表没有动画效果是怎么解决的？

### ISSUE THREAD

**Issue by 6-78** [xlsdg/vue-echarts-v3#54]
line类型图表没有动画效果是怎么解决的？

**Comment by xlsdg** [comment]
检查一下参数配置或到 [echarts.js](https://github.com/ecomfe/echarts/issues) 官方仓库提问。

**Comment by only678** [comment]
好像是组件有问题，我从官网实例中直接拷贝数据过来也是没有动画效果，难道就我自己没有动画效果吗？

**Comment by xlsdg** [comment]
可能与你的配置有关系
