### ISSUE TITLE
填入動態資料的錯誤

### ISSUE THREAD

**Issue by ming7824** [xlsdg/vue-echarts-v3#56]
<template>
    <div class="echarts">
        <IEcharts02 :option="bar" :loading="loading" @ready="onReady" theme="macarons" @click="onClick"/>
    </div>
</template>

<script type="text/babel">
    import IEcharts02 from 'vue-echarts-v3/src/full.vue';
    import 'echarts/theme/macarons.js';
    export default {
        name: 'view',
        components: {
            IEcharts02
        },
        props: {
        },
        data: () => ({
            loading: false,
            bar: {
                title: {
                    text: '平均使用時間'
                },
                tooltip: {},
                xAxis: {
                    data: ['1~10s', '11~20s', '21~30s', '31-40s','41~50s','60s+']
                },
                yAxis: {},
                series: [{
                    name: '使用時間',
                    type: 'bar',
                    data: that.data
                }]
            }
        }),
        methods: {

            onReady(instance) {
                const that = this;

                that.chart = instance;

                console.log(instance);
            },
            onClick(event, instance, echarts) {
                console.log(arguments);
            },
            beforeMount (instance) {
                const that = this;
                var data = [];
                that.chart = instance;
                for (var i = 0; i < 6; i++) {
                data.push(5);
                }
            },
            mounted (instance) {
                const that = this;

                that.chart = instance;

                    that.chart.setOption({
                        series: [{
                            data: that.data
                        }]
                    })

            }
        }
    };
</script>

<style scoped>
    .echarts {
        width: 1800px;
        height: 800px;
    }
</style>

錯誤訊息:

Vue warn]: Error in nextTick: "TypeError: Cannot use 'in' operator to search for '

![image](https://user-images.githubusercontent.com/30595619/32322670-4d771734-c000-11e7-949c-f23d3ddf27e0.png)

**Comment by xlsdg** [comment]
可以详细参照一下使用说明里示例代码
