### ISSUE TITLE
请问怎么注册中国地图

### ISSUE THREAD

**Issue by hank2718** [xlsdg/vue-echarts-v3#6]

**Comment by xlsdg** [comment]
1.按需引入：
import IEcharts from 'vue-echarts-v3/src/lite.vue';
import 'echarts/lib/chart/map';
import 'echarts/lib/chart/effectScatter';
import 'echarts/lib/component/geo';

2.下载地图数据：http://echarts.baidu.com/download-map.html

3.注册地图
调用 IEcharts.registerMap 方法

4.参考官方示例配置参数：http://echarts.baidu.com/demo.html#geo-lines
