### ISSUE TITLE
如何全局引入

### ISSUE THREAD

**Issue by DayangLee** [xlsdg/vue-echarts-v3#66]
您好，项目中需要多个图表组件，目前每个图表组件单独引用都没有问题，但是为了减少项目体积所以希望全局引入一次即可。
我尝试了在main.js中使用以下但是无效：
import IEcharts from 'vue-echarts-v3/src/full.js';
Vue.use(IEcharts)
同时也尝试了在main.js中
import IEcharts from "vue-echarts-v3/src/lite.js";
然后再各个图表组件中具体引入import "echarts/lib/chart/line";等也无效

**Comment by xlsdg** [comment]
无论多少个组件代码里写 `import IEcharts from 'vue-echarts-v3/src/full.js';` ，最后打包的时候 `vue-echarts-v3` 只会打包一次，不会出现引用多次，体积越变越大。

**Comment by DayangLee** [comment]
@xlsdg 好的谢谢

**Comment by tuotuogenjudi** [comment]
不能进行在main中一次引入多个页面使用吗？因为我最初的版本是^1.0.5(当时每个页面引的full.vue), 现在我升版本后,需要改为full.js,这样每个页面都要改引用，很麻烦. @xlsdg

**Comment by xlsdg** [comment]
@tuotuogenjudi 如果老版本使用没有任何问题的话，建议无需升级。由于新版本优化了代码结构，所以会一定程度上带来升级的麻烦。工程里面全局搜索一下 `full.vue` 替换成 `full.js` ，或许难度应该不大。
