### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by yunfengsay** [xlsdg/vue-echarts-v3#67]
![image](https://user-images.githubusercontent.com/15527378/33354883-f7b10eea-d4ef-11e7-8e6f-f7012df1f5cd.png)
![image](https://user-images.githubusercontent.com/15527378/33354904-11d380d2-d4f0-11e7-961b-85e03ee1625f.png)
![image](https://user-images.githubusercontent.com/15527378/33354942-39cab6fa-d4f0-11e7-9516-ef4c0ce4f622.png)
升级了新版本才这样的

退回到 "vue-echarts-v3": "^1.0.4",就好了

**Comment by xlsdg** [comment]
配置一下 `babel` ：

```js
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-echarts-v3/src')]
}
```

**Comment by xlsdg** [comment]
@yunfengsay 路径后面漏了加 `src` 。
