### ISSUE TITLE
if else  更新视图大小的问题

### ISSUE THREAD

**Issue by vonch** [xlsdg/vue-echarts-v3#7]
页面中如果用了if else 那么当为true 的时候 显示出来的 echart 的大小变成初始化的100X100了，这个问题困扰了我好久。

我在官方找到一个解决方法就是使用“style.width和style.height” 但是没法使用100%的样式。有没有什么好的办法呢？

**Comment by xlsdg** [comment]
resizable 属性设置成 true 了吗？

**Comment by vonch** [comment]
搞定了，居然是我没有仔细看文档。早问你就好了，就这一个小问题搞了好几天了。
