### ISSUE TITLE
将IEcharts做成组件，option里面写一些默认的值，其他页面再引用

### ISSUE THREAD

**Issue by cag2050** [xlsdg/vue-echarts-v3#70]
```
import IEcharts from 'vue-echarts-v3/src/full.js';
```
导入vue-echarts-v3后，想将IEcharts做成组件，option里面写一些默认的值；页面引用后，发现不能成功使用或覆盖组件option中默认的值。
请问，有什么好的办法吗？

**Comment by xlsdg** [comment]
有具体的代码示例吗？

**Comment by cag2050** [comment]
@xlsdg 例子地址：https://github.com/cag2050/vue_echarts_v3_demo

**Comment by cag2050** [comment]
我用错组件了，应该用自己写的QueryChart.vue，我再试试

**Comment by alexanderwjz** [comment]
你好，我的项目中引入Vue-echarts-v3模块下theme下的主题可以显示，但引入自己文件夹下存放（包含默认的六个，从theme复制过来的）的主题就不起作用了。这应该是哪里的问题。

**Comment by xlsdg** [comment]
@alexanderwjz 参考一下以往的问题 https://github.com/xlsdg/vue-echarts-v3/issues?utf8=%E2%9C%93&q=%E4%B8%BB%E9%A2%98 ，或者把你的具体代码展示出来。

**Comment by cag2050** [comment]
@xlsdg 还是不能成功使用或覆盖组件option中默认的值。有什么好的办法吗？

**Comment by xlsdg** [comment]
为了实现 `option` 的默认值，再封装一层组件感觉有点多余，而且性能也不好。还不如在传 `option` 的时候，用类似 `lodash.js` 的 [_.merge()](https://lodash.com/docs/4.17.4#merge) 方法去合并默认值来得简单。

**Comment by cag2050** [comment]
@xlsdg 最终，我用 lodash.js 的 merge() 方法做的。
例子地址：https://github.com/cag2050/vue_echarts_v3_demo

**Comment by xlsdg** [comment]
挺好的，赞👍！
