### ISSUE TITLE
legend 和 toolbox 无法显示的老问题

### ISSUE THREAD

**Issue by Yoruichi** [xlsdg/vue-echarts-v3#72]
你好
我翻看了以往的issues，并且找到了一个和legend相关的内容，但我做了对应操作如下

               ` import IEcharts from 'vue-echarts-v3/src/lite.js';`
                `import 'echarts/lib/component/legend';`
                `import 'echarts/lib/component/toolbox';`

之后 legend 仍然没有加载在页面上。 同时，我使用作者提供的Demo 添加legend 并用

                 `npm run dev`

运行，在Demo的页面里也没有显示legend

希望作者能提供一个使用legend和toolbox 的 Demo

感谢

**Comment by xlsdg** [comment]
https://github.com/xlsdg/vue-echarts-v3-demo/blob/master/src/components/Demo06.vue

**Comment by Yoruichi** [comment]
感谢作者，问题已经解决。
