### ISSUE TITLE
1.0.18，版本打包时出错；

### ISSUE THREAD

**Issue by tuotuogenjudi** [xlsdg/vue-echarts-v3#74]
ERROR in static/js/vendor.c9a9c864b4c7d7518d15.js from UglifyJs
Unexpected token: punc ()) [./~/.1.0.18@vue-echarts-v3/src/wrapper.js:43,0][static/js/vendor.c9a9c864b4c7d7518d15.js:108864,18]

**Comment by xlsdg** [comment]
按说明文档配置 `webpack` 了吗？

**Comment by tuotuogenjudi** [comment]
配置了，依旧报错同样的错

**Comment by xlsdg** [comment]
参考一下：https://github.com/xlsdg/vue-echarts-v3-demo

**Comment by tuotuogenjudi** [comment]
include: [resolve('src'), resolve('test'), resolve('node_modules/.1.0.18@vue-echarts-v3/src')],我这边需要加版本才可以

**Comment by xlsdg** [comment]
好吧，跟每个人的 `node` 和 `npm` 版本有关。

**Comment by Sanbingo** [comment]
@tuotuogenjudi 按照你的配置方法，还是会报同样的错误啊~ @xlsdg 我按照配置做的，报同样的问题，“跟每个人的node和npm版本有关”，我的配置Node (V8.9.3)/Npm（5.5.1），请问这怎么配置才行？谢谢~

**Comment by xlsdg** [comment]
@Sanbingo 看看工程里 `node_modules` 文件夹下 `vue-echarts-v3` 的路径。

**Comment by Sanbingo** [comment]
@xlsdg 我确定路径是对的！

**Comment by xlsdg** [comment]
@Sanbingo 有开放的 `github` 示例地址吗？这样方便定位问题。

**Comment by Sanbingo** [comment]
我找到问题了，我在开发的时候这样引用import IEcharts from 'vue-echarts-v3/src/full.js';不会出问题，在部署的时候，因为有用到uglifyjs，所以不能引用src下的文件，改成dist目录构建好的包：import IEcharts from 'vue-echarts-v3/dist/vue-echarts.js';，这样就不会出现打包问题了。

**Comment by xlsdg** [comment]
如果不用按需加载的功能，可以简写成 `import IEcharts from 'vue-echarts-v3';` 等同于 `import IEcharts from 'vue-echarts-v3/dist/vue-echarts.js';`

**Comment by Sanbingo** [comment]
@xlsdg 那webpack还需要配置吗？

**Comment by xlsdg** [comment]
`uglify.js` 会报错，说明还是打包配置问题，建议你还是参考一下 https://github.com/xlsdg/vue-echarts-v3-demo 。

**Comment by xlsdg** [comment]
`import IEcharts from 'vue-echarts-v3';` 这样写就不用修改 `webpack` 的配置了。

**Comment by Sanbingo** [comment]
嗯，好的，多谢耐心指导~
