### ISSUE TITLE
柱状图条数增加后无法减少

### ISSUE THREAD

**Issue by heruns** [xlsdg/vue-echarts-v3#8]
首先非常感谢您的付出,这个插件用起来很好用.
不过目前我遇到一个问题,就是当柱状图series里面只包含一个对象时(即像您的demo那样), push多一个对象进去柱状图可以正常显示两组数据, 但是此时再去掉其中一个或者清空数组重新加入一个对象之后, 此时series中只有一个对象, 但柱状图中依然显示两组数据,这是为何?有没有什么解决办法呢?

**Comment by xlsdg** [comment]
将插件的 notMerge 属性设置成 true 就可以了

**Comment by heruns** [comment]
解决了,非常感谢!

**Comment by Kylexii** [comment]
补充一下，在已有多轴情况下，更新配置对象使轴数量减少等类似场景，都可通过增加notMerge=true解决
