### ISSUE TITLE
更换数据时页面不随之更新

### ISSUE THREAD

**Issue by ws9526** [xlsdg/vue-echarts-v3#80]
![_20180125155055](https://user-images.githubusercontent.com/30396572/35376839-cfc234ac-01e7-11e8-8abf-b6f7f4649b3c.png)
![_20180125154741](https://user-images.githubusercontent.com/30396572/35376847-d61c74b6-01e7-11e8-8612-2389d013ac77.png)
如上图所示，当范围是2014-2017的时候显示四条数据，当换成2016-2017时本应显示两条，但柱状图还是原来的，legend却能发生变化，确认过series是被清空重新赋值的，这种情况只出现在从大的范围到小的范围时

**Comment by xlsdg** [comment]
`notMerge` 参数设成 `true` 了吗？

**Comment by ws9526** [comment]
哦，设置成true就好了，谢谢~
