### ISSUE TITLE
异步加载，datazoom 拖动条的问题

### ISSUE THREAD

**Issue by tonywangcn** [xlsdg/vue-echarts-v3#83]
https://gist.github.com/tonywangcn/36c70653533235efc5013a8db4bb5cb9

若将示例代码中的下述部分取消注释，则为异步加载数据后填充到 echart 中，但遇到的问题时，datazoom 拖动条失效。此时点击还原，拖动条又恢复正常。

请问正确使用异步加载的方法，多谢！

```
var that = this
 setTimeout(function() {
   console.log("sleep 5s")
   that.loading = false
 }, 5000)
```

**Comment by xlsdg** [comment]
代码应该放在 `mounted()` 里，而不是 `created()`。

**Comment by xlsdg** [comment]
异步请求前 `loading = true` ，`option` 设默认配置，看情况配置 `notMerge`，请求到数据之后 `loading = false` ，将数据赋值给 `option` 即可。

**Comment by tonywangcn** [comment]
现在的逻辑就是这样实现的。但“看情况配置 notMerge” 可有文档么？没太理解具体哪些情况，应如何判断

**Comment by xlsdg** [comment]
如果接口返回的数据是全量的，则需要设置 `notMerge` ，反之增量数据不需要。

**Comment by tonywangcn** [comment]
多谢，通过设置 :notMerge="true" 解决了此问题。
