### ISSUE TITLE
部署环境IE11中无法正常使用

### ISSUE THREAD

**Issue by blackcorgi** [xlsdg/vue-echarts-v3#84]
SCRIPT1002: 语法错误 7.0ad6a01a880159759fd3.js (18958,21)

`      styles: {
        type: Object,
        required: false,
        default: () => ({
          width: '100%',
          height: '100%'
        })
      },`

似乎是小括号问题，但是在本地环境下IE并没有提示错误，且可以正常使用

**Comment by xlsdg** [comment]
换成 `import IEcharts from 'vue-echarts-v3';` 试试。

**Comment by blackcorgi** [comment]
多谢，从新部署后IE正常显示，但这是为什么呢？

**Comment by xlsdg** [comment]
可能是 `webpack` 的配置问题，我这边包的路径是 `node_modules/vue-echarts-v3/src` ，你看看工程的 `node_modules` 文件夹里 `vue-echarts-v3` 的路径是什么，然后改一下。

**Comment by blackcorgi** [comment]
路径是一样的。。。估计版本问题么？我这边webpack：2.5.1

**Comment by xlsdg** [comment]
额，应该跟版本没关系
