### ISSUE TITLE
vue-echarts-v3 不支持折线图动画吗？

### ISSUE THREAD

**Issue by jfkued** [xlsdg/vue-echarts-v3#87]
加了动画属性都没有反应，然后默认动画也没有，请问是不支持吗？

**Comment by black-black-cat** [comment]
同问，我也遇到这个问题

**Comment by kazehaiya** [comment]
不支持初始渲染动画问题，添加lazyUpdate属性可渲染

**Comment by kazehaiya** [comment]
问题是会报一个错，Error in nextTick: "TypeError: Cannot read property 'get' of undefined"

**Comment by xlsdg** [comment]
添加 `lazyUpdate` 是可以，报的错可能是 `echarts` 或赋值的问题。
