### ISSUE TITLE
[SVG renderer]  Wrong Axis Popover display when cursor over a chart

### ISSUE THREAD

**Issue by Paul-Kijtapart** [xlsdg/vue-echarts-v3#88]
**Echart version**
"echarts": "^4.0.4",

**OS/Browsers version**
Chrome

**What is Expected?**
When cursor is hover over a Line chart, user should see popover  box over x-axis and y-axis at the coordinate of the hover. 
When renderer (used in initOpts) is set as "svg", the pop-up boxes should have the same style as that of "canvas".

**What is actually happening?**
The popover boxes displayed on x-axis and y-axis is colored black. The labels of the boxes are displayed at the top left corner of the chart instead of on the popover boxes.
https://i.imgur.com/aY5U77m.png

**What I have**
I did import 'zrender/lib/svg/svg'

**Comment by Paul-Kijtapart** [comment]
**Progress**
I found an demo https://github.com/xlsdg/vue-echarts-v3-demo which solves the bug described above.

**Solution**
use echarts 3.8.5 instead of 4.0.4 for now.

**Comment by xlsdg** [comment]
OK.
