### ISSUE TITLE
Charts not updating --> Make notMerge true by default

### ISSUE THREAD

**Issue by SyedWasiHaider** [xlsdg/vue-echarts-v3#89]
Hi there,

Could you please default the notMerge to true by default?

I was setting this.pie.series or this.bar.series and the chart was not updating. For anyone else who runs into this, the work around is to pass a boolean property to the IECharts instance called notMerge so like this:

`      
  <IEcharts :notMerge="notMerge" class="echarts" :option="pie" @ready="onReady" />
`

Then in your data section do this:

```
    data: () => ({
      notMerge:true,
      ...your other props...
    })

```

**Comment by xlsdg** [comment]
Sorry, `notMerge` can not be `true` by default.
