### ISSUE TITLE
echarts  1.0.19 build的时候报错

### ISSUE THREAD

**Issue by shencyber** [xlsdg/vue-echarts-v3#91]
ERROR in static/js/0.9e1892e0478bde10da97.js from Uglify                                                                              Js
Unexpected token: punc ()) [./~/.1.0.19@vue-echarts-v3/s                                                                              rc/wrapper.js:43,0]

**Comment by stanNo1** [comment]
I made a mistake too. Has anybody solved it

**Comment by git8023** [comment]
Me too.  
Hopefully the author can fix it.  

`npm install --save echarts vue-echarts-v3` result of **`"echarts": "^4.1.0"`**

**For Information**
```
Vue.js v2.x+ component wrap for ECharts.js v3.x+
```

**Comment by xlsdg** [comment]
See https://github.com/xlsdg/vue-echarts-v3/issues/74.
