### ISSUE TITLE
地图钻取（全国钻取到省），省份返回全国地图后，再次点击，事件获取的值不正确

### ISSUE THREAD

**Issue by cag2050** [xlsdg/vue-echarts-v3#94]
我做的重现示例项目：https://github.com/cag2050/vue_echarts_v3_demo 。
下载项目，`npm install`后，运行`npm run dev`，访问：http://localhost:9091/ 。
现象描述：1. 第一次点击地图里的“山东”后，成功跳到山东省份地图，event.name 值是“山东”；2. 点击“返回全国地图”后，再次点击地图里的“山东”，不能跳到山东省份地图，event.name 值是空字符串""。
请帮忙看看原因。

**Comment by cag2050** [comment]
最后，采用了权宜之计，点击"返回全国地图"时，直接用`location.reload()`来刷新页面。
demo 地址：https://github.com/cag2050/vue_echarts_v3_demo

**Comment by cag2050** [comment]
最后找到原因了：省份返回全国地图后，没有填充数据的省份，点击时无法获得 event.name 值。
因此，这个地方，要把各省数据填充好。
demo 地址：https://github.com/cag2050/vue_echarts_v3_demo

**Comment by IdenPin** [comment]
@cag2050   你的demo我本地跑了，还是没能获取到name啊 。怎么重新复制name

**Comment by cag2050** [comment]
@IdenPin 初次点击省份，都能获得正确的 event.name 值；点击"返回全国地图"后，只有赋值了的省份，点击时才能正确获得 event.name 值。
