### ISSUE TITLE
结合echarts-gl怎么使用？

### ISSUE THREAD

**Issue by tuotuogenjudi** [xlsdg/vue-echarts-v3#96]
<div class="echarts" style="height: 600px;">
                    <IEcharts :option="topo3" ref="topo3" :loadingOpts="loadingOpts" :loading="load.topoLoading3" :resizable="true" @click="getDetail($event)"></IEcharts>
                  </div>

1. import 'echarts-gl';
2.  import graphGL from '../../../components/echarts/graphGL';
3. topo3: JSON.parse(JSON.stringify(graphGL)),

报错：Uncaught Error: The texture attached to color buffer is not a valid.
    at sub.attach (eval at <anonymous> (0.js:1622), <anonymous>:4264:19)
    at ForceAtlas2GPU._initFromSource (eval at <anonymous> (0.js:1622), <anonymous>:54316:23)
    at ForceAtlas2GPU.step (eval at <anonymous> (0.js:1622), <anonymous>:54162:14)
    at ForceAtlas2GPU.update (eval at <anonymous> (0.js:1622), <anonymous>:54230:14)
    at doLayout (eval at <anonymous> (0.js:1622), <anonymous>:53637:28)
    at eval (eval at <anonymous> (0.js:1622), <anonymous>:53660:13)

**Comment by xlsdg** [comment]
代码：
```vue
<template>
  <div class='echarts'>
    <h2><router-link to="/">Go Back</router-link></h2>
    <IEcharts
      :option='option'
    />
  </div>
</template>

<script>
import IEcharts from 'vue-echarts-v3'
import 'echarts-gl'

export default {
  name: 'Demo07',
  components: {
    IEcharts
  },
  data () {
    return {
      option: {
        grid3D: {},
        xAxis3D: {},
        yAxis3D: {},
        zAxis3D: {},
        series: [{
          type: 'scatter3D',
          symbolSize: 50,
          data: [[-1, -1, -1], [0, 0, 0], [1, 1, 1]],
          itemStyle: {
            opacity: 1
          }
        }]
      }
    }
  },
  methods: {
  }
  // beforeMount () {
  //   const that = this
  // },
  // mounted () {
  //   const that = this
  // },
  // beforeDestroy () {
  //   const that = this
  // }
}
</script>

<!-- Add 'scoped' attribute to limit CSS to this component only -->
<style scoped>
  .echarts {
    width: 800px;
    height: 800px;
    margin: 0 auto;
  }
  h1, h2 {
    font-weight: normal;
  }
  ul {
    list-style-type: none;
    padding: 0;
  }
  li {
    display: inline-block;
    margin: 0 10px;
  }
  a {
    color: #42b983;
  }
</style>
```

示例：
![image](https://user-images.githubusercontent.com/1203305/43952590-f107b282-9cc8-11e8-8ed9-211e51484d1b.png)
