### ISSUE TITLE
How to reduce bundle size

### ISSUE THREAD

**Issue by Pobepto** [xlsdg/vue-echarts-v3#97]
Greetings,

My problem is that I can't reduce bundle size, but I use lite version that you mention in the description of this library. Current size is 1.5 MB.

![image](https://user-images.githubusercontent.com/16295803/43199961-63354572-901c-11e8-9c76-ddd5117880da.png)

In my `.vue` file I have only several lines
``` javascript
import IEcharts from 'vue-echarts-v3/src/lite.js'
import 'echarts/lib/chart/line'
import 'echarts/lib/component/tooltip'
```
The question is why it's take full library and how to reduce it? Also in my project I already has `lodash` is there any way to remove it?

**Comment by pjar** [comment]
@Pobepto have you found a solution?

**Comment by Pobepto** [comment]
@pjar Hi! Yep, as I understand this lib is copy of https://github.com/ecomfe/vue-echarts, so I used `vue-echarts` in our project.

**Comment by TheJedinator** [comment]
Did using the other lib reduce your bundle size? if so by how much? How did you implement it. I have tried both and only saw 180Kb difference.

**Comment by Pobepto** [comment]
> Did using the other lib reduce your bundle size? if so by how much? How did you implement it. I have tried both and only saw 180Kb difference.

The problem I solved is that this library using all features of lodash. In another library (https://github.com/ecomfe/vue-echarts) they used only required features from lodash. Overall this 180 KB was very important for me
